10alsa: various edits
These changes allow the user to check 10alsa's output in
/tmp/services/10alsa.start.log and /tmp/services/10alsa.stop.log

Example: http://pastebin.com/mUFeXJwV

Removed some commented out code.

Wait up to 5 seconds for /dev/mixer to become available (23-29):
This will possibly fix sound detection for some users.

If /dev/mixer is still missing after 5 seconds, then abort because
all the commands that follow will fail:

    ERROR: /dev/mixer is missing
    alsactl: load_state:1686: No soundcards found...
    Failed to save current setup to /etc/asound.state

Indent style changes (this is a "colateral damage")